CREATE TABLE IF NOT EXISTS league_divisions (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    icon VARCHAR(50) NOT NULL,
    tier INTEGER NOT NULL UNIQUE,
    color VARCHAR(20) NOT NULL DEFAULT '#888888',
    min_rank INTEGER NOT NULL DEFAULT 0,
    promotion_slots INTEGER NOT NULL DEFAULT 10,
    demotion_slots INTEGER NOT NULL DEFAULT 5,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
