SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `chat_sessions` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(36) NOT NULL DEFAULT (UUID()),
    `user_id` BIGINT NOT NULL,
    `title` VARCHAR(255),
    `folder_id` BIGINT,
    `summary` TEXT,
    `summary_generated_at` DATETIME,
    `enable_mood_context` TINYINT(1) NOT NULL DEFAULT 1,
    `enable_journal_context` TINYINT(1) NOT NULL DEFAULT 0,
    `enable_daily_task_context` TINYINT(1) NOT NULL DEFAULT 1,
    `enable_xp_level_context` TINYINT(1) NOT NULL DEFAULT 1,
    `enable_playlist_context` TINYINT(1) NOT NULL DEFAULT 0,
    `enable_rewards_context` TINYINT(1) NOT NULL DEFAULT 0,
    `enable_progress_map_context` TINYINT(1) NOT NULL DEFAULT 0,
    `enable_social_context` TINYINT(1) NOT NULL DEFAULT 0,
    `session_intent` VARCHAR(30) NOT NULL DEFAULT 'general',
    `is_favorite` TINYINT(1) DEFAULT 0,
    `is_trash` TINYINT(1) DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted_at` DATETIME,
    PRIMARY KEY (`id`),
    KEY `idx_chat_sessions_deleted_at` (`deleted_at`),
    KEY `idx_chat_sessions_folder` (`folder_id`),
    KEY `idx_chat_sessions_is_favorite` (`is_favorite`),
    KEY `idx_chat_sessions_is_trash` (`is_trash`),
    KEY `idx_chat_sessions_session_intent` (`session_intent`),
    KEY `idx_chat_sessions_user_id` (`user_id`),
    UNIQUE KEY `idx_chat_sessions_uuid` (`uuid`),
    CONSTRAINT `fk_chat_sessions_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
