-- Add missing moderation, profile, and gamification fields to users table
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS suspension_end TIMESTAMP,
ADD COLUMN IF NOT EXISTS suspension_reason TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS is_banned BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS ban_reason TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS has_accepted_a_idisclaimer BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS content_warning_preference VARCHAR(20) DEFAULT 'show',
ADD COLUMN IF NOT EXISTS profile_theme VARCHAR(50) DEFAULT 'default',
ADD COLUMN IF NOT EXISTS profile_banner VARCHAR(500) DEFAULT '',
ADD COLUMN IF NOT EXISTS avatar_border_color VARCHAR(20) DEFAULT '',
ADD COLUMN IF NOT EXISTS tagline VARCHAR(200) DEFAULT '',
ADD COLUMN IF NOT EXISTS bio TEXT DEFAULT '',
ADD COLUMN IF NOT EXISTS current_streak INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS longest_streak INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_activity_date TIMESTAMP,
ADD COLUMN IF NOT EXISTS total_activities INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_login_date DATE,
ADD COLUMN IF NOT EXISTS login_streak INT DEFAULT 0;
