SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `users` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `username` VARCHAR(50) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `role` VARCHAR(20) NOT NULL DEFAULT 'user',
    `exp` BIGINT NOT NULL DEFAULT 0,
    `avatar` VARCHAR(255) DEFAULT '',
    `is_blocked` TINYINT(1) NOT NULL DEFAULT 0,
    `is_forum_blocked` TINYINT(1) DEFAULT 0,
    `reset_token` VARCHAR(255),
    `reset_token_expiry` DATETIME,
    `suspension_end` DATETIME,
    `suspension_reason` TEXT,
    `is_banned` TINYINT(1) NOT NULL DEFAULT 0,
    `ban_reason` TEXT,
    `has_accepted_ai_disclaimer` TINYINT(1) NOT NULL DEFAULT 0,
    `content_warning_preference` VARCHAR(20) NOT NULL DEFAULT 'show',
    `profile_theme` VARCHAR(50) DEFAULT 'default',
    `profile_banner` VARCHAR(500),
    `avatar_border_color` VARCHAR(20),
    `tagline` VARCHAR(200),
    `bio` TEXT,
    `current_streak` BIGINT DEFAULT 0,
    `longest_streak` BIGINT DEFAULT 0,
    `last_activity_date` DATE,
    `total_activities` BIGINT DEFAULT 0,
    `streak_freeze_available` TINYINT(1) DEFAULT 1,
    `streak_freeze_used_at` DATE,
    `last_login_date` DATE,
    `login_streak` BIGINT DEFAULT 0,
    `gold_coins` BIGINT NOT NULL DEFAULT 0,
    `is_premium` TINYINT(1) NOT NULL DEFAULT 0,
    `premium_since` DATETIME,
    `premium_expires_at` DATETIME,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `deleted_at` DATETIME,
    `whatsapp_number` VARCHAR(20) NOT NULL DEFAULT '',
    `whatsapp_verified_at` DATETIME,
    PRIMARY KEY (`id`),
    `whatsapp_verified_key` VARCHAR(20) GENERATED ALWAYS AS (CASE WHEN whatsapp_verified_at IS NOT NULL AND deleted_at IS NULL THEN whatsapp_number END) VIRTUAL,
    UNIQUE KEY `users_email_key` (`email`),
    UNIQUE KEY `uq_users_whatsapp_number_verified` (`whatsapp_verified_key`),
    KEY `idx_users_deleted_at` (`deleted_at`),
    KEY `idx_users_email` (`email`),
    KEY `idx_users_is_banned` (`is_banned`),
    KEY `idx_users_is_blocked` (`is_blocked`),
    KEY `idx_users_role` (`role`),
    KEY `idx_users_suspension_end` (`suspension_end`),
    UNIQUE KEY `idx_users_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
