CREATE TABLE IF NOT EXISTS streak_societies (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    icon VARCHAR(50) NOT NULL,
    min_streak INTEGER NOT NULL UNIQUE,
    border_color VARCHAR(20) NOT NULL DEFAULT '#888888',
    badge_glow BOOLEAN DEFAULT FALSE,
    exclusive_chat BOOLEAN DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
