ALTER TABLE songs
    ADD COLUMN attribution VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN source_url VARCHAR(500) NOT NULL DEFAULT '',
    ADD COLUMN license_url VARCHAR(500) NOT NULL DEFAULT '';
