ALTER TABLE b2b_seat_allocations
DROP CONSTRAINT IF EXISTS uq_b2b_seat_allocations_subscription_member;

DROP INDEX IF EXISTS uq_b2b_seat_allocations_subscription_member_active;

CREATE UNIQUE INDEX uq_b2b_seat_allocations_subscription_member_active
ON b2b_seat_allocations(subscription_id, organization_member_id)
WHERE released_at IS NULL;
